### ISSUE TITLE
building on macOS 10.11 (El Capitan)

### ISSUE THREAD

**Issue by dmsj** [jaymwong/dracula#1]
@jaymwong  This is likely a Drake issue - but curious if you've run into it:

In file included from /Users/dmj4578/drake-distro/drake/common/find_resource.h:8:
/Users/dmj4578/drake-distro/drake/common/drake_optional.h:3:10: fatal error: 
      'stx/optional.hpp' file not found
#include <stx/optional.hpp>

My Drake is the latest master and builds / installs fine.

**Comment by jaymwong** [comment]
As per [#2](https://github.com/jaymwong/dracula/pull/2), `drake/common/find_resource.h` is no longer needed. If this issue continues, make sure the environment variables are set properly as indicated in [README.md](https://github.com/jaymwong/dracula/blob/master/README.md); specifically setting `DRAKE_BUILD_DIR` and `DRAKE_BUILD_DIR`.

**Comment by dmsj** [comment]
Thanks! #2 fixed it.
